spring :
  data :
    mongodb :
      host : localhost
      port : 27017
      database : ezipflix
      collections :
        video-conversions : video_conversions
conversion:
  messaging :
    video-status:
      url: wss://darkops:42308/video_status

cloud:
    project: 'videoconvertering3'
    topic: 'tpconverter'

aws:
  name: 'dynamodb'
  table: 'table_video'
  region: 'eu-west-3'
  s3:
    name: 'edu.esipe.i3.tpvideoconvertering3s3'
    region: 'eu-west-3'
